### ISSUE TITLE
Question about stability

### ISSUE THREAD

**Issue by bentok** [alfonsogarciacaro/fable-flutterapp#1]
@alfonsogarciacaro I know snake island is in alpha. What is your take on the risk of using F# to compile to Flutter now?

Is there high risk of the api changing? More bindings that need to be manually defined? Etc.

I'm curious because I know Python and Rust are also in the release - and presumably some aspects may be more unstable than others.

Thanks!

**Comment by alfonsogarciacaro** [comment]
Hi @bentok, thanks for your questions!

Right now the bindings are basically 1:1 to Flutter API so I don't expect to change. The main difference is in the namespaces because imports work differently in F# and Dart. We had a discussion about how we could improve the namespaces so, if anything, maybe the only thing that changes is the namespaces you need to open (we're trying to reduce them): https://github.com/fable-compiler/Fable/issues/2922

There could be changes in the way code is generated, but this won't likely be a breaking change, because you'll only need to recompile everything with latest Fable version.

Probably more than potential breaking changes the main issue is the missing features at the moment. We're trying to make Fable 4 a collaborative effort, the intention with the alpha release was to get feedback from the users, but it seems many are waiting for a more "stable" release. So we need to turn the vicious circle (users wait for stable release, Fable contributors wait for users' feedback) into a virtuous one (users try the alpha releases and give feedback, Fable contributors know what to prioritize and have examples to test/showcase the compiler) 😄

**Comment by bentok** [comment]
Thanks for the thorough response! This is exactly what I was looking for.  I have an app that is aiming to go to prod in mid-fall, the benefit of using Elmish in Flutter alone makes me willing to deal with those risks.

I will try my best to assist in turning the feedback feedback cycle into a virtuous one.
